//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudioVideoRecorder.Resources.CommonResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AudioVideoRecorder.Resources.CommonResources.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string GetStringByKey(string key) => ResourceManager.GetString(key, resourceCulture);
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutApp {
            get {
                return ResourceManager.GetString("AboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About app.
        /// </summary>
        public static string AboutAppHeader {
            get {
                return ResourceManager.GetString("AboutAppHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is flexible recording software with user-friendly features!
        ///
        ///Using this powerful tool, you can record anything on the screen including selected areas, applications, active windows, and more. There is also an audio recording option for adding your own comments, connect to the webcam, microphone or headphones. {0} lets you optimize the quality of records, apply sound adjustments, save in MP4, MP3, FLAC, WMA and other popular formats.
        ///
        ///We keep on adding new features, working on updates to provide you w [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutInformation {
            get {
                return ResourceManager.GetString("AboutInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent color:.
        /// </summary>
        public static string AccentColor {
            get {
                return ResourceManager.GetString("AccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Task.
        /// </summary>
        public static string AddTask {
            get {
                return ResourceManager.GetString("AddTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After capture:.
        /// </summary>
        public static string AfterCapture {
            get {
                return ResourceManager.GetString("AfterCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animate mouse clicks when recording video.
        /// </summary>
        public static string AnimateMouseClicks {
            get {
                return ResourceManager.GetString("AnimateMouseClicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audios.
        /// </summary>
        public static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio codec:.
        /// </summary>
        public static string AudioCodec {
            get {
                return ResourceManager.GetString("AudioCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio format:.
        /// </summary>
        public static string AudioFormat {
            get {
                return ResourceManager.GetString("AudioFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio quality:.
        /// </summary>
        public static string AudioQuality {
            get {
                return ResourceManager.GetString("AudioQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audios.
        /// </summary>
        public static string Audios {
            get {
                return ResourceManager.GetString("Audios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio settings:.
        /// </summary>
        public static string AudioSettings {
            get {
                return ResourceManager.GetString("AudioSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record is not saved.
        ///Are you sure you want to leave?.
        /// </summary>
        public static string BackDontSave {
            get {
                return ResourceManager.GetString("BackDontSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera:.
        /// </summary>
        public static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start recording with current settings. Attempt to change them or use the default..
        /// </summary>
        public static string CannotStartRecording {
            get {
                return ResourceManager.GetString("CannotStartRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture area:.
        /// </summary>
        public static string CaptureArea {
            get {
                return ResourceManager.GetString("CaptureArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture area border color.
        /// </summary>
        public static string CaptureRegionBorderColor {
            get {
                return ResourceManager.GetString("CaptureRegionBorderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed.
        /// </summary>
        public static string Changed {
            get {
                return ResourceManager.GetString("Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change path and filename.
        /// </summary>
        public static string ChangePathAndFilename {
            get {
                return ResourceManager.GetString("ChangePathAndFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string ChooseColourMode {
            get {
                return ResourceManager.GetString("ChooseColourMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud.
        /// </summary>
        public static string Cloud {
            get {
                return ResourceManager.GetString("Cloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateTask {
            get {
                return ResourceManager.GetString("CreateTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The battery power has reached a critical point, recording is stopped.
        ///If you continue a recording, video can be corrupted.
        ///Would you like to continue the recording now?.
        /// </summary>
        public static string CriticalBatteryPowerLevel {
            get {
                return ResourceManager.GetString("CriticalBatteryPowerLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date must be later than today..
        /// </summary>
        public static string DateErrorMessage {
            get {
                return ResourceManager.GetString("DateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DateOfTask {
            get {
                return ResourceManager.GetString("DateOfTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete file.
        /// </summary>
        public static string DeleteFile {
            get {
                return ResourceManager.GetString("DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the file?.
        /// </summary>
        public static string DeleteFileQuestion {
            get {
                return ResourceManager.GetString("DeleteFileQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The task will be permanently deleted from the recording schedule. Are you sure you want to delete the task?.
        /// </summary>
        public static string DeletingScheduledTask {
            get {
                return ResourceManager.GetString("DeletingScheduledTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop.
        /// </summary>
        public static string Desktop {
            get {
                return ResourceManager.GetString("Desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop &amp; Webcam.
        /// </summary>
        public static string DesktopAndWebcam {
            get {
                return ResourceManager.GetString("DesktopAndWebcam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} disk space remaining.
        /// </summary>
        public static string DiskSpaceRemaining {
            get {
                return ResourceManager.GetString("DiskSpaceRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributed by.
        /// </summary>
        public static string Distributed {
            get {
                return ResourceManager.GetString("Distributed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributed by:.
        /// </summary>
        public static string Distributedby {
            get {
                return ResourceManager.GetString("Distributedby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do Nothing.
        /// </summary>
        public static string DoNothing {
            get {
                return ResourceManager.GetString("DoNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t Save.
        /// </summary>
        public static string DoNotSave {
            get {
                return ResourceManager.GetString("DoNotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t show this dialog again.
        /// </summary>
        public static string DontShowAgain {
            get {
                return ResourceManager.GetString("DontShowAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DropBox.
        /// </summary>
        public static string DropBox {
            get {
                return ResourceManager.GetString("DropBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the record and save the file. Use simple editing tools to make your record perfect..
        /// </summary>
        public static string EditRecord {
            get {
                return ResourceManager.GetString("EditRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit .
        /// </summary>
        public static string EditTask {
            get {
                return ResourceManager.GetString("EditTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end time must be later than the start time..
        /// </summary>
        public static string EndTimeErrorMessage {
            get {
                return ResourceManager.GetString("EndTimeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit {0}.
        /// </summary>
        public static string ExitAppName {
            get {
                return ResourceManager.GetString("ExitAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external power supply was restored.
        ///Would you like to continue the recording?.
        /// </summary>
        public static string ExternalPowerSupplyRestored {
            get {
                return ResourceManager.GetString("ExternalPowerSupplyRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear customer, tell us what you think! Please, enter your feedback:
        ///.
        /// </summary>
        public static string FeedbackMessage {
            get {
                return ResourceManager.GetString("FeedbackMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to access file, check file availability and try again later.
        /// </summary>
        public static string FileCannotAccess {
            get {
                return ResourceManager.GetString("FileCannotAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file was moved or deleted.
        /// </summary>
        public static string FileMovedOrDeleted {
            get {
                return ResourceManager.GetString("FileMovedOrDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        public static string Fullscreen {
            get {
                return ResourceManager.GetString("Fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET NOW.
        /// </summary>
        public static string GetNow {
            get {
                return ResourceManager.GetString("GetNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoogleDrive.
        /// </summary>
        public static string GoogleDrive {
            get {
                return ResourceManager.GetString("GoogleDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide app UI from recording.
        /// </summary>
        public static string HideAppWindowsOnRecordings {
            get {
                return ResourceManager.GetString("HideAppWindowsOnRecordings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide desktop icons.
        /// </summary>
        public static string HideDesktopIcons {
            get {
                return ResourceManager.GetString("HideDesktopIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide panel.
        /// </summary>
        public static string HidePanel {
            get {
                return ResourceManager.GetString("HidePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey.
        /// </summary>
        public static string Hotkey {
            get {
                return ResourceManager.GetString("Hotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkeys.
        /// </summary>
        public static string HotKeys {
            get {
                return ResourceManager.GetString("HotKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open the default mail application. Please check your system settings.
        /// </summary>
        public static string MailCannotAccess {
            get {
                return ResourceManager.GetString("MailCannotAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main page.
        /// </summary>
        public static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string Maximize {
            get {
                return ResourceManager.GetString("Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Features are not installed on your device.{0}The app may not work correctly.{1}Install “Windows Media Player Legacy” in Windows Settings.{2}You can open Settings using the button below.{3}After installation, restart the app and verify video settings before recording..
        /// </summary>
        public static string MediaFeaturesWarning {
            get {
                return ResourceManager.GetString("MediaFeaturesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microphone:.
        /// </summary>
        public static string Microphone {
            get {
                return ResourceManager.GetString("Microphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Store.
        /// </summary>
        public static string MicrosoftStore {
            get {
                return ResourceManager.GetString("MicrosoftStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available microphone is not detected.
        /// </summary>
        public static string MicsAreNotDetected {
            get {
                return ResourceManager.GetString("MicsAreNotDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum free disk space must be {0} megabytes.
        /// </summary>
        public static string MinimumFreeDiskSpace {
            get {
                return ResourceManager.GetString("MinimumFreeDiskSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More apps.
        /// </summary>
        public static string MoreApps {
            get {
                return ResourceManager.GetString("MoreApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most popular.
        /// </summary>
        public static string MostPopular {
            get {
                return ResourceManager.GetString("MostPopular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name field cannot be empty..
        /// </summary>
        public static string NameErrorMessage {
            get {
                return ResourceManager.GetString("NameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Task.
        /// </summary>
        public static string NewTask {
            get {
                return ResourceManager.GetString("NewTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough free disk space.
        /// </summary>
        public static string NoFreeDiskSpace {
            get {
                return ResourceManager.GetString("NoFreeDiskSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available, go to .
        /// </summary>
        public static string NonMandatoryUpdateFirstPart {
            get {
                return ResourceManager.GetString("NonMandatoryUpdateFirstPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and update the app..
        /// </summary>
        public static string NonMandatoryUpdateSecondPart {
            get {
                return ResourceManager.GetString("NonMandatoryUpdateSecondPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to update the app?.
        /// </summary>
        public static string NonMandatoryUpdateText {
            get {
                return ResourceManager.GetString("NonMandatoryUpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there is not enough space on your disk.
        /// </summary>
        public static string NotEnoughSpace {
            get {
                return ResourceManager.GetString("NotEnoughSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneDrive.
        /// </summary>
        public static string OneDrive {
            get {
                return ResourceManager.GetString("OneDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Month.
        /// </summary>
        public static string OneMonth {
            get {
                return ResourceManager.GetString("OneMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On/Off Microphone.
        /// </summary>
        public static string OnOffMicrophone {
            get {
                return ResourceManager.GetString("OnOffMicrophone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On/Off Speakers.
        /// </summary>
        public static string OnOffSpeakers {
            get {
                return ResourceManager.GetString("OnOffSpeakers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn the web camera on/off.
        /// </summary>
        public static string OnOffWebCamera {
            get {
                return ResourceManager.GetString("OnOffWebCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open containing folder.
        /// </summary>
        public static string OpenContainingFolder {
            get {
                return ResourceManager.GetString("OpenContainingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder.
        /// </summary>
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open settings.
        /// </summary>
        public static string OpenSettings {
            get {
                return ResourceManager.GetString("OpenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause recording.
        /// </summary>
        public static string PauseRecord {
            get {
                return ResourceManager.GetString("PauseRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause/resume.
        /// </summary>
        public static string PauseResume {
            get {
                return ResourceManager.GetString("PauseResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, wait.
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published by.
        /// </summary>
        public static string PublishedBy {
            get {
                return ResourceManager.GetString("PublishedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher:.
        /// </summary>
        public static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Us.
        /// </summary>
        public static string RateUs {
            get {
                return ResourceManager.GetString("RateUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        public static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Audio.
        /// </summary>
        public static string RecordAudio {
            get {
                return ResourceManager.GetString("RecordAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording processing....
        /// </summary>
        public static string RecordingProcessing {
            get {
                return ResourceManager.GetString("RecordingProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording Settings.
        /// </summary>
        public static string RecordingSettings {
            get {
                return ResourceManager.GetString("RecordingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record mouse movements.
        /// </summary>
        public static string RecordMouseMovements {
            get {
                return ResourceManager.GetString("RecordMouseMovements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record new audio.
        /// </summary>
        public static string RecordNewAudio {
            get {
                return ResourceManager.GetString("RecordNewAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record new video.
        /// </summary>
        public static string RecordNewVideo {
            get {
                return ResourceManager.GetString("RecordNewVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio: record/stop.
        /// </summary>
        public static string RecordStopAudio {
            get {
                return ResourceManager.GetString("RecordStopAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video: record/stop.
        /// </summary>
        public static string RecordStopVideo {
            get {
                return ResourceManager.GetString("RecordStopVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Video.
        /// </summary>
        public static string RecordVideo {
            get {
                return ResourceManager.GetString("RecordVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rec/Pause Audio.
        /// </summary>
        public static string RecPauseAudio {
            get {
                return ResourceManager.GetString("RecPauseAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rec/Pause Video.
        /// </summary>
        public static string RecPauseVideo {
            get {
                return ResourceManager.GetString("RecPauseVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Ads.
        /// </summary>
        public static string RemoveAds {
            get {
                return ResourceManager.GetString("RemoveAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Watermark.
        /// </summary>
        public static string RemoveWatermark {
            get {
                return ResourceManager.GetString("RemoveWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default settings.
        /// </summary>
        public static string RestoreDefaults {
            get {
                return ResourceManager.GetString("RestoreDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume recording.
        /// </summary>
        public static string ResumeRecord {
            get {
                return ResourceManager.GetString("ResumeRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The disk has run out of free space.
        /// </summary>
        public static string RunOutOfFreeSpace {
            get {
                return ResourceManager.GetString("RunOutOfFreeSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and exit.
        /// </summary>
        public static string SaveAndExit {
            get {
                return ResourceManager.GetString("SaveAndExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveInTheCloud:.
        /// </summary>
        public static string SaveInTheCloud {
            get {
                return ResourceManager.GetString("SaveInTheCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save recording.
        /// </summary>
        public static string SaveRecording {
            get {
                return ResourceManager.GetString("SaveRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to:.
        /// </summary>
        public static string SaveTo {
            get {
                return ResourceManager.GetString("SaveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to cloud:.
        /// </summary>
        public static string SaveToCloud {
            get {
                return ResourceManager.GetString("SaveToCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save window.
        /// </summary>
        public static string SaveWindowTitle {
            get {
                return ResourceManager.GetString("SaveWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure all required fields are filled out correctly.
        /// </summary>
        public static string ScheduleDialogWarningMessage {
            get {
                return ResourceManager.GetString("ScheduleDialogWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a scheduled entry at the specified time.
        /// </summary>
        public static string ScheduledRecord {
            get {
                return ResourceManager.GetString("ScheduledRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduler.
        /// </summary>
        public static string Scheduler {
            get {
                return ResourceManager.GetString("Scheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The battery power has reached a selected percentage, recording is stopped. 
        ///Would you like to continue the recording now?.
        /// </summary>
        public static string SelectedBatteryPowerLevel {
            get {
                return ResourceManager.GetString("SelectedBatteryPowerLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Feedback.
        /// </summary>
        public static string SendFeedback {
            get {
                return ResourceManager.GetString("SendFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share app.
        /// </summary>
        public static string ShareApp {
            get {
                return ResourceManager.GetString("ShareApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoy professional screen recording on Windows! Get started with {0}!{1}.
        /// </summary>
        public static string ShareText {
            get {
                return ResourceManager.GetString("ShareText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show audio panel.
        /// </summary>
        public static string ShowAudioWindow {
            get {
                return ResourceManager.GetString("ShowAudioWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show panel.
        /// </summary>
        public static string ShowPanel {
            get {
                return ResourceManager.GetString("ShowPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show video panel.
        /// </summary>
        public static string ShowVideoWindow {
            get {
                return ResourceManager.GetString("ShowVideoWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown.
        /// </summary>
        public static string Shutdown {
            get {
                return ResourceManager.GetString("Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep.
        /// </summary>
        public static string Sleep {
            get {
                return ResourceManager.GetString("Sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an error has occurred. Would you like to report the error?.
        /// </summary>
        public static string SorryAnErrorOccurred {
            get {
                return ResourceManager.GetString("SorryAnErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start recording.
        /// </summary>
        public static string StartRecord {
            get {
                return ResourceManager.GetString("StartRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start time must be later than now..
        /// </summary>
        public static string StartTimeErrorMessage {
            get {
                return ResourceManager.GetString("StartTimeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch automatically at Windows startup.
        /// </summary>
        public static string StartWithWindows {
            get {
                return ResourceManager.GetString("StartWithWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop:.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop recording.
        /// </summary>
        public static string StopRecord {
            get {
                return ResourceManager.GetString("StopRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop recording when the battery level is below the specified level.
        /// </summary>
        public static string StopRecordingWhenReachBatteryLevel {
            get {
                return ResourceManager.GetString("StopRecordingWhenReachBatteryLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Time.
        /// </summary>
        public static string StopTime {
            get {
                return ResourceManager.GetString("StopTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All PRO Benefits of Screen Recording!
        ///Try out 1 Week for Free!.
        /// </summary>
        public static string SubscriptionDescription {
            get {
                return ResourceManager.GetString("SubscriptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encourage the developers and unlock the full functionality!.
        /// </summary>
        public static string SubscriptionDescriptionATG1 {
            get {
                return ResourceManager.GetString("SubscriptionDescriptionATG1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fist Week for Free! Cancel in any time!.
        /// </summary>
        public static string SubscriptionDescriptionATG2 {
            get {
                return ResourceManager.GetString("SubscriptionDescriptionATG2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The task name can only contain letters and numbers..
        /// </summary>
        public static string TaskNameFieldNamingRule {
            get {
                return ResourceManager.GetString("TaskNameFieldNamingRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule your next video and audio recording by simply adding a task..
        /// </summary>
        public static string TextOfEmptySchedulerPage {
            get {
                return ResourceManager.GetString("TextOfEmptySchedulerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is in use by another application. It can not be deleted now.
        /// </summary>
        public static string TheFileIsUnUse {
            get {
                return ResourceManager.GetString("TheFileIsUnUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme:.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Months.
        /// </summary>
        public static string ThreeMonths {
            get {
                return ResourceManager.GetString("ThreeMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only record 10 minutes with the free version of {0}.
        ///Please purchase PRO version or one of subscriptions..
        /// </summary>
        public static string TimeLimitFreeInfo {
            get {
                return ResourceManager.GetString("TimeLimitFreeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear user! The free version has a 10-minute video recording limit. To record longer videos, purchase the PRO version of the program..
        /// </summary>
        public static string TimeLimitInfo {
            get {
                return ResourceManager.GetString("TimeLimitInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 Months.
        /// </summary>
        public static string TwelveMonths {
            get {
                return ResourceManager.GetString("TwelveMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start camera recording. Please ensure you have granted access to your camera and try again.
        /// </summary>
        public static string UnableStartCameraRecording {
            get {
                return ResourceManager.GetString("UnableStartCameraRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading application updates.
        /// </summary>
        public static string UpdateText {
            get {
                return ResourceManager.GetString("UpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage guidelines.
        /// </summary>
        public static string UsageGuidelines {
            get {
                return ResourceManager.GetString("UsageGuidelines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage {} of {}.
        /// </summary>
        public static string UsageMemory {
            get {
                return ResourceManager.GetString("UsageMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage {0} GB of {1} GB.
        /// </summary>
        public static string UsageMemoryGB {
            get {
                return ResourceManager.GetString("UsageMemoryGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are signed in as .
        /// </summary>
        public static string UserSigned {
            get {
                return ResourceManager.GetString("UserSigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use system settings.
        /// </summary>
        public static string UseSystemSetting {
            get {
                return ResourceManager.GetString("UseSystemSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video codec:.
        /// </summary>
        public static string VideoCodec {
            get {
                return ResourceManager.GetString("VideoCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video encoder:.
        /// </summary>
        public static string VideoEncoder {
            get {
                return ResourceManager.GetString("VideoEncoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video format:.
        /// </summary>
        public static string VideoFormat {
            get {
                return ResourceManager.GetString("VideoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video quality:.
        /// </summary>
        public static string VideoQuality {
            get {
                return ResourceManager.GetString("VideoQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Video.
        /// </summary>
        public static string VideoRecordWindowTitle {
            get {
                return ResourceManager.GetString("VideoRecordWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        public static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video settings:.
        /// </summary>
        public static string VideoSettings {
            get {
                return ResourceManager.GetString("VideoSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The free version will add a watermark to your recorded video.{0}To save videos without a watermark, please upgrade to the PRO version or get a subscription..
        /// </summary>
        public static string WatermarkWarning {
            get {
                return ResourceManager.GetString("WatermarkWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webcam.
        /// </summary>
        public static string Webcam {
            get {
                return ResourceManager.GetString("Webcam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn’t retrieve webcam information. Please restart the application..
        /// </summary>
        public static string WebcamError {
            get {
                return ResourceManager.GetString("WebcamError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available webcam is not detected.
        /// </summary>
        public static string WebCamsAreNotDetected {
            get {
                return ResourceManager.GetString("WebCamsAreNotDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 WEEK FREE.
        /// </summary>
        public static string WeekFree {
            get {
                return ResourceManager.GetString("WeekFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no available schedules.
        /// </summary>
        public static string YouHaveNoScheduleRecords {
            get {
                return ResourceManager.GetString("YouHaveNoScheduleRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no recorded audios.
        /// </summary>
        public static string YouNaveNoRecordedAudios {
            get {
                return ResourceManager.GetString("YouNaveNoRecordedAudios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no recorded videos.
        /// </summary>
        public static string YouNaveNoRecordedVideos {
            get {
                return ResourceManager.GetString("YouNaveNoRecordedVideos", resourceCulture);
            }
        }
    }
}
